### ISSUE TITLE
System error: BLAST failed abruptly (exit status: 135). Most likely there is a problem with the BLAST+ binaries.

### ISSUE THREAD

**Issue by yondchang** [wurmlab/sequenceserver#623]
I am using sequenceserver docker version with NCBI NR database and got a system error.

System error
Looks like there is a problem with the server. Try visiting the page again after a while. If this message persists, please report the problem on our [issue tracker](https://github.com/wurmlab/sequenceserver/issues).

BLAST failed abruptly (exit status: 135). Most likely there is a
problem with the BLAST+ binaries.   

This NCBI NR database is huge (>500GB), not sure this is the reason.
Any idea? 
thanks.

**Comment by yannickwurm** [comment]
Hello @yondchang  - I suspect that BLAST against NR is using too much RAM. I suggest trying to run the blast in the command line. 
(sometimes a corrupted download of nr can also make things crash).

**Comment by yondchang** [comment]
Thanks for the tip, you are absolutely right, command line gives me a bus error (core dumped)

**Comment by yannickwurm** [comment]
(FYI we had a situation where blast 2.12 on ubuntu was inexplicably giving this for some queries... but not for others... which was resolved when switching to 2.13. So if the nr download is intact and there is enough ram, this would be a 3rd thing to look at). 

Take care

**Comment by yondchang** [comment]
@yannickwurm : I've tried expanding memory to 64G but still no luck, the blast version is the latest 2.13.0, anyway I can check the error with more details? right now it just says Bus error (core dumped)
thanks for your help

**Comment by yondchang** [comment]
Alright, turns out this is not a memory issue but due to a corrupted file during unzip process, thanks all the same.

**Comment by yannickwurm** [comment]
Ah - thank you for the update @yondchang  - I'm happy to hear that you solved it...
